export const gestures = [
  ["嚎啕大哭", "射击", "旱鸭子", "小鸟依人", "打嗝", "扭秧歌", "一毛不拔", "孙悟空", "暴跳如雷", "淘宝", "大跌眼镜", "八卦", "画饼充饥", "奶瓶", "羊入虎口", "闭月羞花", "足球", "泰山压顶", "打酱油", "老鹰", "皮鞋", "加油站"],
  ["香蕉", "猩猩", "井底之蛙", "吃货", "击剑", "一石二鸟", "啤酒肚", "含笑九泉", "我爱你", "睡觉", "吃里扒外", "机不可失", "打麻将", "呆若木鸡", "大眼瞪小眼", "百里挑一", "鼠标", "一刀两断", "井底之蛙", "嬉皮笑脸", "香水", "开膛破肚", "鸭子", "七上八下", "方便面", "外星人", "熊猫"],
  ["企鹅", "心花怒放", "见钱眼开", "西瓜", "流口水", "馒头", "牛头马面", "鸡飞蛋打", "豆腐", "狗急跳墙", "油条", "张牙舞爪", "回眸一笑", "美女", "照镜子", "秋裤", "灭火器", "看破红尘", "害羞", "牛头马面", "遛狗", "王者荣耀", "狗拿耗子"],
  ["猪八戒", "跪地求饶", "最炫民族风", "打呼噜", "跨栏", "石榴", "洗澡", "狼吞虎咽", "沉鱼落雁", "公鸡打鸣", "海枯石烂", "手套", "斗地主", "狼心狗肺", "老鼠", "拔河", "飞机", "弱不禁风", "女汉子", "痛哭流涕", "苹果", "鹤立鸡群", "贼眉鼠眼 ", "卫生纸", "斩草除根", "减肥", "拍马屁", "朝三暮四"],
  ["奥特曼", "枕头", "囫囵吞枣", "矿泉水", "兔死狐悲", "茶叶蛋", "初恋", "手舞足蹈", "铁路", "苦尽甘来", "肯德基", "春运", "龙马精神", "花好月圆", "保安", "锦上添花", "毛笔", "草莓", "隔岸观火"],
  ["灯笼", "快板", "发热", "臭美", "愤怒", "教师节", "哭闹", "肌肉注射", "酱油", "花生油", "月亮", "喷香水", "吃面条", "夜宵", "假货", "和尚", "系鞋带", "抹指甲油", "心肺复苏", "发冷", "车票", "尼姑", "星星", "存折", "妇女节", "新生儿", "老师", "减肥", "不及格", "比赛", "淘宝网", "骑自行车", "撒腿就跑", "中大奖", "医院", "包饺子"],
  ['7猴子捞月', '猪八戒背媳妇', '嫦娥奔月', '后裔射日', '精卫填海', '画饼充饥', '三打白骨精', '黛玉葬花'],
  ['8猴子捞月', '猪八戒背媳妇', '嫦娥奔月', '后裔射日', '精卫填海', '画饼充饥', '三打白骨精', '黛玉葬花'],
  ['9猴子捞月', '猪八戒背媳妇', '嫦娥奔月', '后裔射日', '精卫填海', '画饼充饥', '三打白骨精', '黛玉葬花']
]
export const brands = [
  [
    { img: './logos/b_1.png', answer: '阿斯顿·马丁-英国' },
    { img: './logos/a_2.jpeg', answer: '碧欧泉-法国' },
    { img: './logos/b_2.png', answer: '北汽-中国' },
    { img: './logos/b_3.png', answer: '本田-日本' },
    { img: './logos/b_4.png', answer: '奔腾-中国' },
    { img: './logos/b_5.png', answer: '拉达-俄罗斯' },
    { img: './logos/a_1.jpeg', answer: '香奈儿-法国' },
    { img: './logos/b_6.png', answer: '宝马-德国' },
    { img: './logos/b_7.png', answer: '昌河-中国' },
    { img: './logos/b_8.png', answer: '布嘉迪-法国' },
    { img: './logos/b_9.png', answer: '阿尔法罗米欧-意大利' },
    { img: './logos/b_10.png', answer: '宝骏-中国' },
    { img: './logos/b_93.png', answer: '川汽野马-中国' },
    { img: './logos/b_12.png', answer: '长城-中国' },
    { img: './logos/a_3.jpeg', answer: '芳珂-日本' }
  ],
  [
    { img: './logos/b_13.png', answer: '标致-法国' },
    { img: './logos/b_87.png', answer: '瑞麒-中国' },
    { img: './logos/a_4.jpeg', answer: '希思黎-法国' },
    { img: './logos/b_80.png', answer: '大发-日本' },
    { img: './logos/a_5.jpeg', answer: '肌肤之钥-日本' },
    { img: './logos/b_16.png', answer: '长安-中国' },
    { img: './logos/b_17.png', answer: '长丰-中国' },
    { img: './logos/b_18.png', answer: '法拉利-意大利' },
    { img: './logos/a_6.jpeg', answer: '悦木之源-美国' },
    { img: './logos/b_19.png', answer: '丰田-日本' },
    { img: './logos/b_20.png', answer: '东风-中国' },
    { img: './logos/b_21.png', answer: '观致-中国' },
    { img: './logos/b_22.png', answer: '克莱斯勒-美国' },
    { img: './logos/b_23.png', answer: '福特-美国' },
    { img: './logos/b_24.png', answer: '海马-中国' },
  ],
  [
    { img: './logos/b_25.png', answer: '广汽-中国' },
    { img: './logos/b_26.png', answer: '华普-中国' },
    { img: './logos/b_27.png', answer: '雪佛兰-美国' },
    { img: './logos/a_9.jpeg', answer: '安娜苏-法国' },
    { img: './logos/b_28.png', answer: '夏利-中国' },
    { img: './logos/b_29.png', answer: '一汽-中国' },
    { img: './logos/b_30.png', answer: '众泰-中国' },
    { img: './logos/a_8.jpeg', answer: '娇兰-法国' },
    { img: './logos/b_31.png', answer: '永源-中国' },
    { img: './logos/a_7.jpeg', answer: '雅诗兰黛-法国' },
    { img: './logos/b_32.png', answer: 'smart-德国' },
    { img: './logos/b_33.png', answer: '威兹曼-德国' },
    { img: './logos/b_34.png', answer: '福田-中国' },
    { img: './logos/b_35.png', answer: '雪铁龙-法国' },
    { img: './logos/b_36.png', answer: '现代-韩国' },
  ],
  [
    { img: './logos/b_37.png', answer: '西亚特-西班牙' },
    { img: './logos/b_38.png', answer: '吉奥-中国' },
    { img: './logos/b_39.png', answer: '中兴-中国' },
    { img: './logos/a_12.jpeg', answer: '纪梵希-法国' },
    { img: './logos/b_40.png', answer: '中华-中国' },
    { img: './logos/a_11.jpeg', answer: '科颜氏-美国' },
    { img: './logos/b_41.png', answer: '英伦-中国' },
    { img: './logos/b_42.png', answer: '英菲尼迪-日本' },
    { img: './logos/b_43.png', answer: '五菱汽车-中国' },
    { img: './logos/b_44.png', answer: '威麟-中国' },
    { img: './logos/b_45.png', answer: '沃尔沃-瑞典' },
    { img: './logos/b_46.png', answer: '华泰-中国' },
    { img: './logos/b_47.png', answer: '哈飞-中国' },
    { img: './logos/b_48.png', answer: '捷豹-英国' },
    { img: './logos/a_13.jpeg', answer: '迪奥-法国' },
  ],
  [
    { img: './logos/b_49.png', answer: '江淮-中国' },
    { img: './logos/b_50.png', answer: '黄海-中国' },
    { img: './logos/b_51.png', answer: '金杯-中国' },
    { img: './logos/a_14.jpeg', answer: '圣罗兰-法国' },
    { img: './logos/b_52.png', answer: '吉利-中国' },
    { img: './logos/b_53.png', answer: '劳斯莱斯-英国' },
    { img: './logos/b_54.png', answer: '三菱-日本' },
    { img: './logos/a_15.jpeg', answer: '赫莲娜-法国' },
    { img: './logos/b_55.png', answer: '日产-日本' },
    { img: './logos/b_56.png', answer: '奇瑞-中国' },
    { img: './logos/b_57.png', answer: '双龙-韩国' },
    { img: './logos/a_16.jpeg', answer: '娇韵诗-法国' },
    { img: './logos/b_58.png', answer: '世爵-荷兰' },
    { img: './logos/b_59.png', answer: '奔驰-德国' },
    { img: './logos/b_60.png', answer: '凯迪拉克-美国' },
  ],
  [
    { img: './logos/b_61.png', answer: '雷克萨斯-日本' },
    { img: './logos/b_62.png', answer: '开瑞-中国' },
    { img: './logos/b_63.png', answer: '兰博基尼-意大利' },
    { img: './logos/a_24.jpeg', answer: '植村秀-日本' },
    { img: './logos/b_64.png', answer: '柯尼赛格-瑞典' },
    { img: './logos/b_65.png', answer: '雷诺-法国' },
    { img: './logos/a_23.jpeg', answer: '茵芙纱-日本' },
    { img: './logos/b_66.png', answer: '林肯-美国' },
    { img: './logos/b_67.png', answer: '保时捷-德国' },
    { img: './logos/b_68.png', answer: 'MG-英国' },
    { img: './logos/b_69.png', answer: '迈巴赫-德国' },
    { img: './logos/b_70.png', answer: '路虎-英国' },
    { img: './logos/b_71.png', answer: '玛莎拉蒂-意大利' },
    { img: './logos/b_72.png', answer: '领克-中国' },
    { img: './logos/a_10.jpeg', answer: '魅可-加拿大' }
  ],
  [
    { img: './logos/b_73.png', answer: '菲亚特-意大利' },
    { img: './logos/b_74.png', answer: '东南-中国' },
    { img: './logos/a_18.jpeg', answer: '茱莉蔻-澳大利亚' },
    { img: './logos/b_75.png', answer: '荣威-中国' },
    { img: './logos/b_76.png', answer: '铃木-日本' },
    { img: './logos/a_17.jpeg', answer: '莱伯妮-瑞士' },
    { img: './logos/b_77.png', answer: '力帆-中国' },
    { img: './logos/b_78.png', answer: '斯柯达-德国' },
    { img: './logos/b_79.png', answer: '双环-中国' },
    { img: './logos/b_15.png', answer: '宾利-英国' },
    { img: './logos/a_19.jpeg', answer: '贝玲妃-美国' },
    { img: './logos/b_81.png', answer: '斯巴鲁-日本' },
    { img: './logos/b_82.png', answer: '纳智捷-中国' },
    { img: './logos/b_83.png', answer: '道奇-美国' },
    { img: './logos/b_84.png', answer: '陆风-中国' },
  ],
  [
    { img: './logos/b_85.png', answer: 'MINI-英国' },
    { img: './logos/b_86.png', answer: '马自达-日本' },
    { img: './logos/a_22.jpeg', answer: '海蓝之谜-美国' },
    { img: './logos/b_14.png', answer: '别克-美国' },
    { img: './logos/b_88.png', answer: '欧宝-德国' },
    { img: './logos/a_20.jpeg', answer: '资生堂-日本' },
    { img: './logos/b_89.png', answer: '讴歌-日本' },
    { img: './logos/a_21.jpeg', answer: '欧舒丹-法国' },
    { img: './logos/b_90.png', answer: '大众-德国' },
    { img: './logos/b_91.png', answer: '帕加尼-意大利' },
    { img: './logos/b_92.png', answer: '萨博-瑞典' },
    { img: './logos/b_11.png', answer: '奥迪-德国' },
    { img: './logos/b_94.png', answer: '江铃-中国' },
    { img: './logos/b_95.png', answer: '宝沃-中国' },
    { img: './logos/b_96.png', answer: '起亚-韩国' },
  ]
]
