export const gestures = [
    ['去','我','呃','人'],
    ['他','有','우','이'],
    ['ㅍ','啊','是','에'],
]
export const brands = [
  [
    { img: './logos/b_1.png', answer: '阿斯顿·马丁-英国' },
    { img: './logos/a_2.jpeg', answer: '碧欧泉-法国' },
    { img: './logos/b_2.png', answer: '北汽-中国' },
    { img: './logos/b_3.png', answer: '本田-日本' },
    { img: './logos/b_4.png', answer: '奔腾-中国' },
    { img: './logos/b_5.png', answer: '拉达-俄罗斯' },
    { img: './logos/a_1.jpeg', answer: '香奈儿-法国' },
    { img: './logos/b_6.png', answer: '宝马-德国' },
    { img: './logos/b_7.png', answer: '昌河-中国' },
    { img: './logos/b_8.png', answer: '布嘉迪-法国' },
    { img: './logos/b_9.png', answer: '阿尔法罗米欧-意大利' },
    { img: './logos/b_10.png', answer: '宝骏-中国' },
    { img: './logos/b_93.png', answer: '川汽野马-中国' },
    { img: './logos/b_12.png', answer: '长城-中国' },
    { img: './logos/a_3.jpeg', answer: '芳珂-日本' }
  ],
  [
    { img: './logos/b_13.png', answer: '标致-法国' },
    { img: './logos/b_87.png', answer: '瑞麒-中国' },
    { img: './logos/a_4.jpeg', answer: '希思黎-法国' },
    { img: './logos/b_80.png', answer: '大发-日本' },
    { img: './logos/a_5.jpeg', answer: '肌肤之钥-日本' },
    { img: './logos/b_16.png', answer: '长安-中国' },
    { img: './logos/b_17.png', answer: '长丰-中国' },
    { img: './logos/b_18.png', answer: '法拉利-意大利' },
    { img: './logos/a_6.jpeg', answer: '悦木之源-美国' },
    { img: './logos/b_19.png', answer: '丰田-日本' },
    { img: './logos/b_20.png', answer: '东风-中国' },
    { img: './logos/b_21.png', answer: '观致-中国' },
    { img: './logos/b_22.png', answer: '克莱斯勒-美国' },
    { img: './logos/b_23.png', answer: '福特-美国' },
    { img: './logos/b_24.png', answer: '海马-中国' },
  ],
  [
    { img: './logos/b_25.png', answer: '广汽-中国' },
    { img: './logos/b_26.png', answer: '华普-中国' },
    { img: './logos/b_27.png', answer: '雪佛兰-美国' },
    { img: './logos/a_9.jpeg', answer: '安娜苏-法国' },
    { img: './logos/b_28.png', answer: '夏利-中国' },
    { img: './logos/b_29.png', answer: '一汽-中国' },
    { img: './logos/b_30.png', answer: '众泰-中国' },
    { img: './logos/a_8.jpeg', answer: '娇兰-法国' },
    { img: './logos/b_31.png', answer: '永源-中国' },
    { img: './logos/a_7.jpeg', answer: '雅诗兰黛-法国' },
    { img: './logos/b_32.png', answer: 'smart-德国' },
    { img: './logos/b_33.png', answer: '威兹曼-德国' },
    { img: './logos/b_34.png', answer: '福田-中国' },
    { img: './logos/b_35.png', answer: '雪铁龙-法国' },
    { img: './logos/b_36.png', answer: '现代-韩国' },
  ],
  [
    { img: './logos/b_37.png', answer: '西亚特-西班牙' },
    { img: './logos/b_38.png', answer: '吉奥-中国' },
    { img: './logos/b_39.png', answer: '中兴-中国' },
    { img: './logos/a_12.jpeg', answer: '纪梵希-法国' },
    { img: './logos/b_40.png', answer: '中华-中国' },
    { img: './logos/a_11.jpeg', answer: '科颜氏-美国' },
    { img: './logos/b_41.png', answer: '英伦-中国' },
    { img: './logos/b_42.png', answer: '英菲尼迪-日本' },
    { img: './logos/b_43.png', answer: '五菱汽车-中国' },
    { img: './logos/b_44.png', answer: '威麟-中国' },
    { img: './logos/b_45.png', answer: '沃尔沃-瑞典' },
    { img: './logos/b_46.png', answer: '华泰-中国' },
    { img: './logos/b_47.png', answer: '哈飞-中国' },
    { img: './logos/b_48.png', answer: '捷豹-英国' },
    { img: './logos/a_13.jpeg', answer: '迪奥-法国' },
  ],
  [
    { img: './logos/b_49.png', answer: '江淮-中国' },
    { img: './logos/b_50.png', answer: '黄海-中国' },
    { img: './logos/b_51.png', answer: '金杯-中国' },
    { img: './logos/a_14.jpeg', answer: '圣罗兰-法国' },
    { img: './logos/b_52.png', answer: '吉利-中国' },
    { img: './logos/b_53.png', answer: '劳斯莱斯-英国' },
    { img: './logos/b_54.png', answer: '三菱-日本' },
    { img: './logos/a_15.jpeg', answer: '赫莲娜-法国' },
    { img: './logos/b_55.png', answer: '日产-日本' },
    { img: './logos/b_56.png', answer: '奇瑞-中国' },
    { img: './logos/b_57.png', answer: '双龙-韩国' },
    { img: './logos/a_16.jpeg', answer: '娇韵诗-法国' },
    { img: './logos/b_58.png', answer: '世爵-荷兰' },
    { img: './logos/b_59.png', answer: '奔驰-德国' },
    { img: './logos/b_60.png', answer: '凯迪拉克-美国' },
  ],
  [
    { img: './logos/b_61.png', answer: '雷克萨斯-日本' },
    { img: './logos/b_62.png', answer: '开瑞-中国' },
    { img: './logos/b_63.png', answer: '兰博基尼-意大利' },
    { img: './logos/a_24.jpeg', answer: '植村秀-日本' },
    { img: './logos/b_64.png', answer: '柯尼赛格-瑞典' },
    { img: './logos/b_65.png', answer: '雷诺-法国' },
    { img: './logos/a_23.jpeg', answer: '茵芙纱-日本' },
    { img: './logos/b_66.png', answer: '林肯-美国' },
    { img: './logos/b_67.png', answer: '保时捷-德国' },
    { img: './logos/b_68.png', answer: 'MG-英国' },
    { img: './logos/b_69.png', answer: '迈巴赫-德国' },
    { img: './logos/b_70.png', answer: '路虎-英国' },
    { img: './logos/b_71.png', answer: '玛莎拉蒂-意大利' },
    { img: './logos/b_72.png', answer: '领克-中国' },
    { img: './logos/a_10.jpeg', answer: '魅可-加拿大' }
  ],
  [
    { img: './logos/b_73.png', answer: '菲亚特-意大利' },
    { img: './logos/b_74.png', answer: '东南-中国' },
    { img: './logos/a_18.jpeg', answer: '茱莉蔻-澳大利亚' },
    { img: './logos/b_75.png', answer: '荣威-中国' },
    { img: './logos/b_76.png', answer: '铃木-日本' },
    { img: './logos/a_17.jpeg', answer: '莱伯妮-瑞士' },
    { img: './logos/b_77.png', answer: '力帆-中国' },
    { img: './logos/b_78.png', answer: '斯柯达-德国' },
    { img: './logos/b_79.png', answer: '双环-中国' },
    { img: './logos/b_15.png', answer: '宾利-英国' },
    { img: './logos/a_19.jpeg', answer: '贝玲妃-美国' },
    { img: './logos/b_81.png', answer: '斯巴鲁-日本' },
    { img: './logos/b_82.png', answer: '纳智捷-中国' },
    { img: './logos/b_83.png', answer: '道奇-美国' },
    { img: './logos/b_84.png', answer: '陆风-中国' },
  ],
  [
    { img: './logos/b_85.png', answer: 'MINI-英国' },
    { img: './logos/b_86.png', answer: '马自达-日本' },
    { img: './logos/a_22.jpeg', answer: '海蓝之谜-美国' },
    { img: './logos/b_14.png', answer: '别克-美国' },
    { img: './logos/b_88.png', answer: '欧宝-德国' },
    { img: './logos/a_20.jpeg', answer: '资生堂-日本' },
    { img: './logos/b_89.png', answer: '讴歌-日本' },
    { img: './logos/a_21.jpeg', answer: '欧舒丹-法国' },
    { img: './logos/b_90.png', answer: '大众-德国' },
    { img: './logos/b_91.png', answer: '帕加尼-意大利' },
    { img: './logos/b_92.png', answer: '萨博-瑞典' },
    { img: './logos/b_11.png', answer: '奥迪-德国' },
    { img: './logos/b_94.png', answer: '江铃-中国' },
    { img: './logos/b_95.png', answer: '宝沃-中国' },
    { img: './logos/b_96.png', answer: '起亚-韩国' },
  ]
]
